### PR TITLE
Defer auth-source-pick-first-password call

### LINKED ISSUE #10: auth-source stops emacs daemon from starting
When using a gpg encrypted authinfo file, due to this code:

```elisp
(defun aichat-openai-api-key ()
  "Get openai api key from `auth-sources'."
  (auth-source-pick-first-password :host "platform.openai.com" :user "aichat-openai"))
```

The user will be prompted for their gpg passphrase, which is fine when starting Emacs in the foreground.

However, if Emacs is started in the background, for example using Emacs Daemon, it will just keep it from fully loading, as the user will never have access to the gpg prompt.

I'm suggesting wrapping `auth-source-pick-first-password` in a lambda like this:

```elisp
(defun aichat-openai-api-key ()
  "Get openai api key from `auth-sources'."
  (lambda () (auth-source-pick-first-password :host "platform.openai.com" :user "aichat-openai")))
```

This will return a closure and defer the `auth-source-pick-first-password` call, allowing proper load of Emacs in the background.

### PR DESCRIPTION
**Pull request by MunsterPlop**
- Closes #10

### CODE REVIEW

**Comment by xhcoding** [comment]
This code patch will cause errors where it is called

emacs calls this function at startup because the following variable definition calls it


https://github.com/xhcoding/emacs-aichat/blob/153f92d87f53908fe96e5ef99945bdc92ece87b8/aichat-openai.el#L112-L114

Maybe we should change `defvar` to `defun`, and get the key at runtime instead of at require time

**Comment by MunsterPlop** [comment]
Indeed, I overlooked this. That's what happens when you stay up too long. I'm gonna sleep for now and will look into that tomorrow.

**Comment by MunsterPlop** [comment]
Alright, I couldn't help but put something together before sleeping so here's my suggested change:

```elisp
(defcustom aichat-openai-api-key nil
  "OpenAI key as a string or a function that loads and returns it."
  :type '(choice (function :tag "Function")
                 (string :tag "String"))
  :group 'aichat-openai)
```

Turn `aichat-openai--http-headers` into:

```elisp
(defun aichat-openai--make-http-headers ()
  "Create http headers to send in requests to the API."
  `(("Content-Type" . "application/json")
    ("Authorization" . ,(format "Bearer %s" (if (functionp aichat-openai-api-key)
                                                (funcall aichat-openai-api-key)
                                              aichat-openai-api-key)))))
```

Then replace
```elisp
          :headers aichat-openai--http-headers
```
with
```elisp
          :headers (aichat-openai--make-http-headers)
```

It would also require updating the documentation to mention you have to explicitely set `aichat-openai-api-key`.

There's obviously some error handling to do when the api-key hasn't been set.
I will take care of that tomorrow if you're okay with the whole idea.

**Comment by xhcoding** [comment]
Thanks, I appreciate that and think it's ok for me.

**Comment by xhcoding** [comment]
Thanks for your patch.

I don't usually use OpenAI, so there are only two demo functions showing API calls in `emacs-openai.el.` If you are an OpenAI user, please feel free to submit a PR to implement useful or interesting features using OpenAI.

**Pull request merged**
